import type { Metadata } from "next";
import { Bona_Nova, Cormorant_Garamond, Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const bonaNova = Bona_Nova({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-bonaNova",
});
const cormorant = Cormorant_Garamond({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-cormorant",
});
const arial = localFont({
  src: [
    {
      path: "../../public/fonts/arial.ttf",
    },
  ],
  variable: "--font-arial",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bonaNova.variable} ${cormorant.variable} ${arial.variable}`}>
        {children}
      </body>
    </html>
  );
}
