import type { Metadata } from "next";
import { Bona_Nova, Cormorant_Garamond, Inter } from "next/font/google";
import "./globals.css";

const bonaNova = Bona_Nova({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-bonaNova",
});
const cormorant = Cormorant_Garamond({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-cormorant",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bonaNova.variable} ${cormorant.variable}`}>
        {children}
      </body>
    </html>
  );
}
